no exception when no stats folder exists
sladkoff/minecraft-prometheus-exporter pull request #78
Opened 2021-05-06 09:47 UTC by galexrt

Signed-off-by: Alexander Trost <galexrt@googlemail.com>

Resolves #77

2021-05-07 04:28 UTC, weihao approved these changes
Solves this error:

```
survival_1       | [07:00:15 INFO]: [PrometheusExporter] Enabling PrometheusExporter v2.4.0
survival_1       | [07:00:15 INFO]: [PrometheusExporter] Reading player stats from folder  /data/world/stats
survival_1       | [07:00:15 INFO]: [PrometheusExporter] Error - abandoning file reading
survival_1       | [07:00:15 WARN]: java.nio.file.NoSuchFileException: /data/world/stats
survival_1       | [07:00:15 WARN]:     at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.Files.readAttributes(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.FileTreeWalker.visit(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.FileTreeWalker.walk(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.FileTreeIterator.<init>(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.Files.walk(Unknown Source)
survival_1       | [07:00:15 WARN]:     at java.base/java.nio.file.Files.walk(Unknown Source)
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromFile.readPlayerStatsFiles(PlayerStatisticLoaderFromF
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromFile.<init>(PlayerStatisticLoaderFromFile.java:43)
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.metrics.PlayerStatistics.<init>(PlayerStatistics.java:40)
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.config.MetricConfig.getMetric(MetricConfig.java:20)
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.config.PrometheusExporterConfig.lambda$enableConfiguredMetrics$1(PrometheusExporterConfig.ja
survival_1       | [07:00:15 WARN]:     at java.base/java.util.Arrays$ArrayList.forEach(Unknown Source)
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.config.PrometheusExporterConfig.enableConfiguredMetrics(PrometheusExporterConfig.java:61)
survival_1       | [07:00:15 WARN]:     at de.sldk.mc.PrometheusExporter.onEnable(PrometheusExporter.java:18)
survival_1       | [07:00:15 WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
survival_1       | [07:00:15 WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
survival_1       | [07:00:15 WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
survival_1       | [07:00:15 WARN]:     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
survival_1       | [07:00:15 WARN]:     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
survival_1       | [07:00:15 WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
survival_1       | [07:00:15 WARN]:     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
survival_1       | [07:00:15 WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
survival_1       | [07:00:15 WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
survival_1       | [07:00:15 WARN]:     at java.base/java.lang.Thread.run(Unknown Source)
survival_1       | [07:00:15 INFO]: [org.eclipse.jetty.server.Server] jetty-11.0.1; built: 2021-02-19T22:03:05.556Z; git: e98092c1791fbda9d157dd53
survival_1       | [07:00:16 INFO]: [org.eclipse.jetty.server.AbstractConnector] Started ServerConnector@2f540ef9{HTTP/1.1, (http/1.1)}{0.0.0.0:92
survival_1       | [07:00:16 INFO]: [org.eclipse.jetty.server.Server] Started Server@7a1c6bab{STARTING}[11.0.1,sto=0] @47444m
```

2021-05-08 16:25 UTC, sladkoff requested changes
@galexrt Thanks for the contribution! Could you check why the CI can't compile this. Cheers.

2021-05-08 16:25 UTC, sladkoff commented on src/main/java/de/sldk/mc/metrics/player/PlayerStatisticLoaderFromFile.java
> +            if (!statsFolder.exists()) {
This doesn't compile on the CI with Java 11. Could you double-check?

2021-05-08 16:25 UTC, sladkoff commented on src/main/java/de/sldk/mc/metrics/player/PlayerStatisticLoaderFromFile.java
> +            // If the stats folder doesn't exist, don't bother reading it
Feel free to drop the comment. The code is pretty self-explanatory :rocket:

2021-05-08 16:32 UTC, galexrt commented
@sladkoff Fixed.

BTW My IDE is warning me about `Resource leak: 'statFiles' is never closed.` on line 73.

2021-05-08 16:36 UTC, sladkoff commented
@galexrt Good catch! Would you mind fixing that up, too :) 
A try-with-resources block should probably work fine there.

2021-05-08 16:41 UTC, galexrt commented
@sladkoff Done, pushed in a second commit. :)

2021-05-08 16:45 UTC, merged